//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelesApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllProduct
    {
        public AllProduct()
        {
            this.PurchBillDetails = new HashSet<PurchBillDetail>();
            this.SelesBillDetails = new HashSet<SelesBillDetail>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> PurchPrice { get; set; }
        public Nullable<decimal> SellingPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<PurchBillDetail> PurchBillDetails { get; set; }
        public virtual ICollection<SelesBillDetail> SelesBillDetails { get; set; }
    }
}
