//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelesApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CustomerDebts = new HashSet<CustomerDebt>();
            this.SelesBills = new HashSet<SelesBill>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Notes { get; set; }
        public string Phone { get; set; }
        public string Company { get; set; }
        public string Email { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> TotalDebt { get; set; }
    
        public virtual ICollection<CustomerDebt> CustomerDebts { get; set; }
        public virtual ICollection<SelesBill> SelesBills { get; set; }
    }
}
