//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelesApp.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SelesAppEntities : DbContext
    {
        public SelesAppEntities()
            : base("name=SelesAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AllProduct> AllProducts { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<CustomerDebt> CustomerDebts { get; set; }
        public DbSet<PurchBill> PurchBills { get; set; }
        public DbSet<PurchBillDetail> PurchBillDetails { get; set; }
        public DbSet<SelesBill> SelesBills { get; set; }
        public DbSet<SelesBillDetail> SelesBillDetails { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<Suppler> Supplers { get; set; }
        public DbSet<SupplerDebt> SupplerDebts { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
