//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelesApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchBillDetail
    {
        public int id { get; set; }
        public Nullable<int> ProdID { get; set; }
        public Nullable<int> PurchBillID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> TotalSub { get; set; }
        public string ItemName { get; set; }
    
        public virtual AllProduct AllProduct { get; set; }
        public virtual PurchBill PurchBill { get; set; }
    }
}
