//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelesApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchBill
    {
        public PurchBill()
        {
            this.PurchBillDetails = new HashSet<PurchBillDetail>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Notes { get; set; }
        public Nullable<int> SupplerID { get; set; }
        public Nullable<decimal> TotalOfBill { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalAfterDiscount { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual Suppler Suppler { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<PurchBillDetail> PurchBillDetails { get; set; }
    }
}
