//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelesApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplerDebt
    {
        public int id { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> SupplerID { get; set; }
        public string KindOfOP { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> TotalResult { get; set; }
    
        public virtual Suppler Suppler { get; set; }
    }
}
